/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "tertiary": "#943700",
        "surface-container": "#ededf9",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "surface-variant": "#e1e2ed",
        "primary": "#004ac6",
        "surface-container-high": "#e7e7f3",
        "surface-container-low": "#f3f3fe",
        "secondary-fixed": "#eaddff",
        "inverse-surface": "#2e3039",
        "on-surface-variant": "#434655",
        "tertiary-fixed-dim": "#ffb596",
        "on-primary-container": "#eeefff",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-container": "#fffbff",
        "inverse-on-surface": "#f0f0fb",
        "on-background": "#191b23",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#5a00c6",
        "surface": "#faf8ff",
        "on-surface": "#191b23",
        "primary-fixed": "#dbe1ff",
        "secondary-container": "#8a4cfc",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdbcd",
        "surface-container-highest": "#e1e2ed",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-bright": "#faf8ff",
        "tertiary-container": "#bc4800",
        "on-tertiary-fixed": "#360f00",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#d2bbff",
        "outline": "#737686",
        "secondary": "#712ae2",
        "surface-dim": "#d9d9e5",
        "outline-variant": "#c3c6d7",
        "background": "#faf8ff",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed": "#00174b"
      },
      spacing: {
        "2xl": "3rem",
        "xs": "0.25rem",
        "md": "1rem",
        "base": "4px",
        "gutter": "1.5rem",
        "sm": "0.5rem",
        "xl": "2rem",
        "container-max": "1440px",
        "lg": "1.5rem"
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
